### PR TITLE
Follow up to Improved readability in docs - css builds #19

### PR DESCRIPTION
**Pull request by dvesh3**
Follow up to #19 
Before:
image

After:
image

### CODE REVIEW

**Comment by dvesh3** [comment]
we have to reconsider the theme changes introduced in #19 as the new theme changes the color background to light.

**Comment by NiklasBr** [comment]
I think the changes significantly increased contrast and readability. Any examples where id did not?

**Comment by dvesh3** [comment]
@NiklasBr I have created a poll for the community to vote for the preferred color scheme. please see  https://github.com/pimcore/pimcore/discussions/13236

**Comment by NiklasBr** [comment]
@dvesh3 I replied. This should not be just about *preference* as you claim. I made this change for actual physical human reasons, not just personal preference, which is why I was confused why you reverted it.

**Comment by dvesh3** [comment]
@NiklasBr We never reverted the change as it was not applied ever(due to the missing build changes) like you see in the description. I created a poll for the community so that we can come to a conclusion as after generating the build we were not sure to apply the changes.

**Comment by NiklasBr** [comment]
@dvesh3 Seems like a bad way to go about it to ask about *preference* rather than *accessibility requirements* and long-term HID needs. I'm just trying to help here and improve things which should not be subject to just emotional aspects but medical ones.

**Comment by brusch** [comment]
Obsolete

**Pull request closed without merging**
