### PR TITLE
Improved readability in docs

### LINKED ISSUE #14: Dark default text is not readable
See for example: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Deeplinks_into_Admin_Interface.html

image

### PR DESCRIPTION
**Pull request by NiklasBr**
Resolves #14 

I have always had problems with this, hope this gets accepted

### CODE REVIEW

**Comment by brusch** [comment]
@NiklasBr can you please sign the CLA? Thanks a lot 😊

**Comment by NiklasBr** [comment]
Let's wait a few days with these changes @brusch, might have a couple of more improvements in the pipeline

**Comment by brusch** [comment]
@NiklasBr alright, thanks! 😊

**Comment by dvesh3** [comment]
@NiklasBr Is it ready for review now?

**Comment by NiklasBr** [comment]
Yes it is, sorry I lost track of this. Could not find anything else to adjust.

**Comment by dvesh3** [comment]
@NiklasBr thanks!

**Comment by NiklasBr** [comment]
These changes never took effect on the site?

**Comment by dvesh3** [comment]
can you please share the example link?

**Comment by NiklasBr** [comment]
First change `@code-background-color` `#f7f7f7` is still `#002b36`

image

**Comment by dvesh3** [comment]
> First change `@code-background-color` `#f7f7f7` is still `#002b36`
> 
> image

@NiklasBr The reason for the change never took effect is the css syles generated builds were not pushed along with the `less` changes. I created a follow up PR https://github.com/pimcore/pimcore-docs/pull/23

**Comment by NiklasBr** [comment]
Aha, thanks @dvesh3! Didn't check for generated styles, probably assumed they were built on deploy.

**Pull request merged**
